// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package mailgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mailreq struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mailreq) Reset()         { *m = Mailreq{} }
func (m *Mailreq) String() string { return proto.CompactTextString(m) }
func (*Mailreq) ProtoMessage()    {}
func (*Mailreq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *Mailreq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mailreq.Unmarshal(m, b)
}
func (m *Mailreq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mailreq.Marshal(b, m, deterministic)
}
func (m *Mailreq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mailreq.Merge(m, src)
}
func (m *Mailreq) XXX_Size() int {
	return xxx_messageInfo_Mailreq.Size(m)
}
func (m *Mailreq) XXX_DiscardUnknown() {
	xxx_messageInfo_Mailreq.DiscardUnknown(m)
}

var xxx_messageInfo_Mailreq proto.InternalMessageInfo

func (m *Mailreq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Mailreq) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type Mailres struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mailres) Reset()         { *m = Mailres{} }
func (m *Mailres) String() string { return proto.CompactTextString(m) }
func (*Mailres) ProtoMessage()    {}
func (*Mailres) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{1}
}

func (m *Mailres) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mailres.Unmarshal(m, b)
}
func (m *Mailres) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mailres.Marshal(b, m, deterministic)
}
func (m *Mailres) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mailres.Merge(m, src)
}
func (m *Mailres) XXX_Size() int {
	return xxx_messageInfo_Mailres.Size(m)
}
func (m *Mailres) XXX_DiscardUnknown() {
	xxx_messageInfo_Mailres.DiscardUnknown(m)
}

var xxx_messageInfo_Mailres proto.InternalMessageInfo

func (m *Mailres) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*Mailreq)(nil), "mailgrpc.mailreq")
	proto.RegisterType((*Mailres)(nil), "mailgrpc.mailres")
}

func init() {
	proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b)
}

var fileDescriptor_7cda5f053e74676b = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0xb1, 0xd3, 0x8b, 0x0a, 0x92, 0x95, 0x8c,
	0xb9, 0xd8, 0x41, 0xec, 0xa2, 0xd4, 0x42, 0x21, 0x3e, 0x2e, 0xa6, 0x92, 0x7c, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0xa6, 0x92, 0x7c, 0x21, 0x09, 0x2e, 0xf6, 0xe2, 0xd2, 0xa4, 0xac, 0xd4,
	0xe4, 0x12, 0x09, 0x26, 0xb0, 0x20, 0x8c, 0xab, 0x24, 0x0b, 0xd3, 0x54, 0x2c, 0x24, 0xc4, 0xc5,
	0x92, 0x99, 0x97, 0x06, 0xd3, 0x06, 0x66, 0x1b, 0x99, 0x70, 0xb1, 0xf8, 0x26, 0x66, 0xe6, 0x08,
	0xe9, 0x70, 0xb1, 0x04, 0xa7, 0xe6, 0xa5, 0x08, 0x09, 0xea, 0xc1, 0xac, 0xd3, 0x83, 0xda, 0x25,
	0x85, 0x21, 0x54, 0xec, 0xc4, 0x13, 0xc5, 0xa5, 0x67, 0x0d, 0x13, 0x4d, 0x62, 0x03, 0x3b, 0xd4,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xe5, 0xd5, 0xf4, 0xb6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MailClient is the client API for Mail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailClient interface {
	Send(ctx context.Context, in *Mailreq, opts ...grpc.CallOption) (*Mailres, error)
}

type mailClient struct {
	cc grpc.ClientConnInterface
}

func NewMailClient(cc grpc.ClientConnInterface) MailClient {
	return &mailClient{cc}
}

func (c *mailClient) Send(ctx context.Context, in *Mailreq, opts ...grpc.CallOption) (*Mailres, error) {
	out := new(Mailres)
	err := c.cc.Invoke(ctx, "/mailgrpc.Mail/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServer is the server API for Mail service.
type MailServer interface {
	Send(context.Context, *Mailreq) (*Mailres, error)
}

// UnimplementedMailServer can be embedded to have forward compatible implementations.
type UnimplementedMailServer struct {
}

func (*UnimplementedMailServer) Send(ctx context.Context, req *Mailreq) (*Mailres, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterMailServer(s *grpc.Server, srv MailServer) {
	s.RegisterService(&_Mail_serviceDesc, srv)
}

func _Mail_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mailreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mailgrpc.Mail/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).Send(ctx, req.(*Mailreq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mailgrpc.Mail",
	HandlerType: (*MailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Mail_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
