// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbgrpc.proto

package dbgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	Surname              string   `protobuf:"bytes,1,opt,name=surname,proto3" json:"surname,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Date                 string   `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c45d6e931c7470, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Profile) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Profile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c45d6e931c7470, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *AuthResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AuthRequest struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Profile              *Profile `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c45d6e931c7470, []int{2}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *AuthRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *AuthRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "dbgrpc.profile")
	proto.RegisterType((*AuthResponse)(nil), "dbgrpc.authResponse")
	proto.RegisterType((*AuthRequest)(nil), "dbgrpc.authRequest")
}

func init() {
	proto.RegisterFile("dbgrpc.proto", fileDescriptor_e3c45d6e931c7470)
}

var fileDescriptor_e3c45d6e931c7470 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x68, 0x9b, 0x96, 0x6b, 0x25, 0xa4, 0xa3, 0x83, 0xd5, 0x01, 0xa1, 0x4c, 0x20, 0xa4,
	0x08, 0xca, 0x08, 0x4b, 0x2b, 0x04, 0x7b, 0x46, 0x36, 0xc7, 0x76, 0x89, 0xa5, 0x34, 0x0e, 0xb6,
	0x23, 0xc4, 0xa7, 0xc0, 0xd7, 0xa2, 0x9c, 0x93, 0x50, 0x10, 0x0b, 0xdb, 0xbd, 0xf7, 0xce, 0xef,
	0xde, 0x9d, 0x0c, 0x0b, 0x99, 0xbf, 0xd8, 0x5a, 0xa4, 0xb5, 0x35, 0xde, 0x60, 0x1c, 0x50, 0xf2,
	0x11, 0xc1, 0xb4, 0xb6, 0x66, 0xa7, 0x4b, 0x85, 0x0c, 0xa6, 0xae, 0xb1, 0x15, 0xdf, 0x2b, 0x16,
	0x9d, 0x47, 0x17, 0xc7, 0x59, 0x0f, 0x11, 0x61, 0x4c, 0xf4, 0x11, 0xd1, 0x54, 0xe3, 0x12, 0x26,
	0x6a, 0xcf, 0x75, 0xc9, 0x46, 0x44, 0x06, 0x80, 0x2b, 0x98, 0xe5, 0xda, 0xfa, 0x42, 0xf2, 0x77,
	0x36, 0x26, 0x61, 0xc0, 0xad, 0x8b, 0xe4, 0x5e, 0xb1, 0x49, 0x70, 0x69, 0xeb, 0xb6, 0xbf, 0xe6,
	0xce, 0xbd, 0x19, 0x2b, 0x59, 0x1c, 0xfa, 0x7b, 0x9c, 0xdc, 0xc3, 0x82, 0x37, 0xbe, 0xc8, 0x94,
	0xab, 0x4d, 0xe5, 0x28, 0x85, 0xae, 0x76, 0xa6, 0x0b, 0x47, 0x75, 0xc8, 0x2c, 0x84, 0x72, 0x8e,
	0xc2, 0xcd, 0xb2, 0x1e, 0x26, 0x1e, 0xe6, 0xe1, 0xf5, 0x6b, 0xa3, 0x9c, 0x6f, 0x07, 0x95, 0x46,
	0x70, 0xaf, 0x4d, 0xd5, 0x19, 0x0c, 0x18, 0xcf, 0x00, 0x84, 0x29, 0x4b, 0x25, 0x48, 0x0d, 0x4b,
	0x1e, 0x30, 0x78, 0x39, 0xdc, 0x88, 0x96, 0x9d, 0xaf, 0x4f, 0xd2, 0xef, 0x63, 0xb6, 0x74, 0xd6,
	0xeb, 0xeb, 0xcf, 0x08, 0xe2, 0x4d, 0xe3, 0x8b, 0x87, 0x2d, 0x5e, 0xc3, 0x68, 0x23, 0x25, 0x9e,
	0xf6, 0xbd, 0x07, 0x69, 0x56, 0xcb, 0x9f, 0x64, 0xb7, 0xe0, 0x15, 0x8c, 0x9e, 0x94, 0xff, 0xfb,
	0xc5, 0xef, 0x91, 0x78, 0x03, 0xe3, 0x47, 0x5d, 0xfd, 0xc7, 0x7f, 0x0b, 0xcf, 0xb3, 0xf4, 0x2e,
	0x08, 0x79, 0x4c, 0xff, 0xe0, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x75, 0x2f, 0x54, 0x17,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthDBClient is the client API for AuthDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthDBClient interface {
	Add(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Get(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*Profile, error)
	Find(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authDBClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthDBClient(cc grpc.ClientConnInterface) AuthDBClient {
	return &authDBClient{cc}
}

func (c *authDBClient) Add(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/dbgrpc.AuthDB/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authDBClient) Get(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/dbgrpc.AuthDB/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authDBClient) Find(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/dbgrpc.AuthDB/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthDBServer is the server API for AuthDB service.
type AuthDBServer interface {
	Add(context.Context, *AuthRequest) (*AuthResponse, error)
	Get(context.Context, *AuthRequest) (*Profile, error)
	Find(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedAuthDBServer can be embedded to have forward compatible implementations.
type UnimplementedAuthDBServer struct {
}

func (*UnimplementedAuthDBServer) Add(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedAuthDBServer) Get(ctx context.Context, req *AuthRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedAuthDBServer) Find(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterAuthDBServer(s *grpc.Server, srv AuthDBServer) {
	s.RegisterService(&_AuthDB_serviceDesc, srv)
}

func _AuthDB_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthDBServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbgrpc.AuthDB/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthDBServer).Add(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbgrpc.AuthDB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthDBServer).Get(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthDB_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthDBServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbgrpc.AuthDB/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthDBServer).Find(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbgrpc.AuthDB",
	HandlerType: (*AuthDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AuthDB_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AuthDB_Get_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _AuthDB_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbgrpc.proto",
}
