// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	Surname              string   `protobuf:"bytes,1,opt,name=surname,proto3" json:"surname,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Date                 string   `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Profile) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Profile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Req struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Req) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type Res struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Res) Reset()         { *m = Res{} }
func (m *Res) String() string { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()    {}
func (*Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Res.Unmarshal(m, b)
}
func (m *Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Res.Marshal(b, m, deterministic)
}
func (m *Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Res.Merge(m, src)
}
func (m *Res) XXX_Size() int {
	return xxx_messageInfo_Res.Size(m)
}
func (m *Res) XXX_DiscardUnknown() {
	xxx_messageInfo_Res.DiscardUnknown(m)
}

var xxx_messageInfo_Res proto.InternalMessageInfo

func (m *Res) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Res) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Profile)(nil), "authgrpc.profile")
	proto.RegisterType((*Req)(nil), "authgrpc.req")
	proto.RegisterType((*Res)(nil), "authgrpc.res")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x9b, 0x26, 0x75, 0xac, 0x07, 0x17, 0x0f, 0x4b, 0x4f, 0x92, 0x83, 0x0a, 0x4a,
	0x0e, 0xf5, 0xe8, 0x49, 0x0f, 0x82, 0x20, 0x08, 0xd5, 0x5e, 0xbc, 0x6d, 0x93, 0xb1, 0x09, 0xb4,
	0xbb, 0xdb, 0xdd, 0x09, 0xe2, 0x4f, 0xf1, 0x87, 0xf9, 0x7f, 0x64, 0x37, 0xdd, 0x14, 0x2f, 0x86,
	0xde, 0xe6, 0xbd, 0x79, 0x7c, 0xf3, 0x12, 0x16, 0x40, 0x34, 0x54, 0xe5, 0xda, 0x28, 0x52, 0x6c,
	0xec, 0xe6, 0x95, 0xd1, 0x45, 0xf6, 0x1d, 0x41, 0xaa, 0x8d, 0xfa, 0xa8, 0xd7, 0xc8, 0x38, 0xa4,
	0xb6, 0x31, 0x52, 0x6c, 0x90, 0x47, 0xe7, 0xd1, 0xd5, 0xd1, 0x3c, 0x48, 0xc6, 0x20, 0xf6, 0xf6,
	0xc0, 0xdb, 0x7e, 0x66, 0x67, 0x30, 0xc2, 0x8d, 0xa8, 0xd7, 0x7c, 0xe8, 0xcd, 0x56, 0xb0, 0x29,
	0x8c, 0x97, 0xb5, 0xa1, 0xaa, 0x14, 0x5f, 0x3c, 0xf6, 0x8b, 0x4e, 0x3b, 0x4a, 0x29, 0x08, 0xf9,
	0xa8, 0xa5, 0xb8, 0xd9, 0xe5, 0xb5, 0xb0, 0xf6, 0x53, 0x99, 0x92, 0x27, 0x6d, 0x3e, 0xe8, 0xec,
	0x11, 0x86, 0x06, 0xb7, 0xec, 0xba, 0x6b, 0xe8, 0x6b, 0x1d, 0xcf, 0x4e, 0xf3, 0x50, 0x3f, 0xdf,
	0x2d, 0xe6, 0xdd, 0x37, 0x84, 0x1b, 0x83, 0xfd, 0x8d, 0xec, 0xd9, 0x71, 0xec, 0x61, 0x1c, 0x0e,
	0x69, 0xa1, 0x24, 0xa1, 0xa4, 0x1d, 0x2a, 0xc8, 0xd9, 0x4f, 0x04, 0xf1, 0x1b, 0x5a, 0x62, 0x17,
	0x90, 0xbc, 0xd6, 0x2b, 0xb9, 0xd0, 0xec, 0x64, 0x0f, 0x32, 0xb8, 0x9d, 0xfe, 0x91, 0x36, 0xe4,
	0x9e, 0x64, 0x7f, 0x6e, 0xa1, 0xfd, 0x4f, 0xf9, 0x3f, 0x77, 0x09, 0xa9, 0xe3, 0xbd, 0x34, 0xd4,
	0x13, 0xbc, 0x81, 0xc9, 0x7d, 0x43, 0x15, 0x4a, 0xaa, 0x8b, 0x5e, 0xec, 0xc3, 0xe4, 0x1d, 0xf2,
	0xbb, 0xe0, 0x2c, 0x13, 0xff, 0x50, 0x6e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x12, 0xee, 0xa7,
	0xad, 0x36, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	SignUp(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	SignIn(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	SignOut(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	Authenticate(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type testClient struct {
	cc grpc.ClientConnInterface
}

func NewTestClient(cc grpc.ClientConnInterface) TestClient {
	return &testClient{cc}
}

func (c *testClient) SignUp(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Test/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) SignIn(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Test/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Test/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) SignOut(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Test/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) Authenticate(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Test/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	SignUp(context.Context, *Req) (*Res, error)
	SignIn(context.Context, *Req) (*Res, error)
	Update(context.Context, *Req) (*Res, error)
	SignOut(context.Context, *Req) (*Res, error)
	Authenticate(context.Context, *Req) (*Res, error)
}

// UnimplementedTestServer can be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (*UnimplementedTestServer) SignUp(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedTestServer) SignIn(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedTestServer) Update(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedTestServer) SignOut(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}
func (*UnimplementedTestServer) Authenticate(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Test/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).SignUp(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Test/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).SignIn(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Test/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Update(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Test/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).SignOut(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Test/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Authenticate(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authgrpc.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _Test_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _Test_SignIn_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Test_Update_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _Test_SignOut_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _Test_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
