// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	Surname              string   `protobuf:"bytes,1,opt,name=surname,proto3" json:"surname,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Date                 string   `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	AccountValidation    string   `protobuf:"bytes,7,opt,name=accountValidation,proto3" json:"accountValidation,omitempty"`
	Admin                string   `protobuf:"bytes,8,opt,name=admin,proto3" json:"admin,omitempty"`
	XId                  string   `protobuf:"bytes,9,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Profile) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Profile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Profile) GetAccountValidation() string {
	if m != nil {
		return m.AccountValidation
	}
	return ""
}

func (m *Profile) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *Profile) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

type Req struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Req) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type Res struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Res) Reset()         { *m = Res{} }
func (m *Res) String() string { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()    {}
func (*Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Res.Unmarshal(m, b)
}
func (m *Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Res.Marshal(b, m, deterministic)
}
func (m *Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Res.Merge(m, src)
}
func (m *Res) XXX_Size() int {
	return xxx_messageInfo_Res.Size(m)
}
func (m *Res) XXX_DiscardUnknown() {
	xxx_messageInfo_Res.DiscardUnknown(m)
}

var xxx_messageInfo_Res proto.InternalMessageInfo

func (m *Res) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Res) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Profile)(nil), "authgrpc.profile")
	proto.RegisterType((*Req)(nil), "authgrpc.req")
	proto.RegisterType((*Res)(nil), "authgrpc.res")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0xc6, 0xd9, 0xfe, 0xdb, 0x76, 0xde, 0xbe, 0x48, 0x83, 0x87, 0xd0, 0x93, 0xec, 0x41, 0x05,
	0xcb, 0x1e, 0xea, 0xd1, 0x93, 0x1e, 0x84, 0x82, 0x20, 0xac, 0xd4, 0x83, 0x17, 0x49, 0x93, 0xd8,
	0x0d, 0xec, 0x26, 0x69, 0x36, 0xab, 0xf8, 0xa5, 0xfd, 0x08, 0x22, 0xc9, 0x36, 0x5b, 0x44, 0x70,
	0xf1, 0x36, 0xcf, 0x33, 0x3f, 0x9e, 0xcc, 0x0c, 0x01, 0x20, 0xb5, 0xcd, 0x53, 0x6d, 0x94, 0x55,
	0x68, 0xec, 0xea, 0xad, 0xd1, 0x34, 0xf9, 0x88, 0x20, 0xd6, 0x46, 0xbd, 0x88, 0x82, 0x23, 0x0c,
	0x71, 0x55, 0x1b, 0x49, 0x4a, 0x8e, 0xa3, 0x93, 0xe8, 0x7c, 0x92, 0x05, 0x89, 0x10, 0x0c, 0xbc,
	0xdd, 0xf3, 0xb6, 0xaf, 0xd1, 0x31, 0x0c, 0x79, 0x49, 0x44, 0x81, 0xfb, 0xde, 0x6c, 0x04, 0x9a,
	0xc3, 0x78, 0x23, 0x8c, 0xcd, 0x19, 0x79, 0xc7, 0x03, 0xdf, 0x68, 0xb5, 0x4b, 0x61, 0xc4, 0x72,
	0x3c, 0x6c, 0x52, 0x5c, 0xed, 0x78, 0x4d, 0xaa, 0xea, 0x4d, 0x19, 0x86, 0x47, 0x0d, 0x1f, 0x34,
	0x5a, 0xc0, 0x8c, 0x50, 0xaa, 0x6a, 0x69, 0x1f, 0x49, 0x21, 0x18, 0xb1, 0x42, 0x49, 0x1c, 0x7b,
	0xe8, 0x67, 0xc3, 0xcd, 0x43, 0x58, 0x29, 0x24, 0x1e, 0x37, 0xf3, 0x78, 0x81, 0x8e, 0xa0, 0xff,
	0x2c, 0x18, 0x9e, 0x78, 0xaf, 0xb7, 0x62, 0xc9, 0x2d, 0xf4, 0x0d, 0xdf, 0xa1, 0x8b, 0x76, 0x6d,
	0xbf, 0xeb, 0xbf, 0xe5, 0x2c, 0x0d, 0x37, 0x49, 0xf7, 0x8d, 0xac, 0x3d, 0x4c, 0x18, 0xbc, 0x77,
	0x18, 0x3c, 0xb9, 0x73, 0x39, 0xd5, 0xdf, 0x72, 0x30, 0xc4, 0x54, 0x49, 0xcb, 0xa5, 0xdd, 0x47,
	0x05, 0xb9, 0xfc, 0x8c, 0x60, 0x70, 0x5d, 0xdb, 0x1c, 0x9d, 0xc2, 0xe8, 0x41, 0x6c, 0xe5, 0x5a,
	0xa3, 0xff, 0x87, 0x20, 0xc3, 0x77, 0xf3, 0x6f, 0xb2, 0x0a, 0xdc, 0x4a, 0x76, 0x73, 0x6b, 0xed,
	0x2f, 0xfd, 0x3b, 0x77, 0x06, 0xb1, 0xcb, 0xbb, 0xaf, 0x6d, 0x37, 0x98, 0x71, 0xaa, 0x5e, 0xb9,
	0xe9, 0x00, 0x17, 0x30, 0x75, 0x1b, 0x71, 0x69, 0x05, 0xed, 0x7c, 0xff, 0x66, 0xfa, 0x04, 0xe9,
	0x55, 0x70, 0x36, 0x23, 0xff, 0x4d, 0x2f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xc5, 0x81,
	0x4c, 0xb4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	SignUp(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	SignIn(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	SignOut(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	Recover(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	Authenticate(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) SignUp(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Auth/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SignIn(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Auth/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Auth/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SignOut(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Auth/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Recover(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Auth/Recover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Authenticate(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/authgrpc.Auth/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	SignUp(context.Context, *Req) (*Res, error)
	SignIn(context.Context, *Req) (*Res, error)
	Update(context.Context, *Req) (*Res, error)
	SignOut(context.Context, *Req) (*Res, error)
	Recover(context.Context, *Req) (*Res, error)
	Authenticate(context.Context, *Req) (*Res, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) SignUp(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedAuthServer) SignIn(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAuthServer) Update(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedAuthServer) SignOut(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}
func (*UnimplementedAuthServer) Recover(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recover not implemented")
}
func (*UnimplementedAuthServer) Authenticate(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Auth/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SignUp(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Auth/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SignIn(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Auth/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Update(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Auth/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SignOut(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Recover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Recover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Auth/Recover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Recover(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.Auth/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Authenticate(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authgrpc.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _Auth_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _Auth_SignIn_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Auth_Update_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _Auth_SignOut_Handler,
		},
		{
			MethodName: "Recover",
			Handler:    _Auth_Recover_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _Auth_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
