export enum typeofAction {
	AUTH = "AUTH",

	NEWSLETTERS = "NEWSLETTERS",

	CARTSEND = "CARTSEND",
	ADD_TO_CART = "ADD_TO_CART",
	REMOVE_TO_CART = "ADD_TO_CART",
	CHANGE_QUANTITY = "CHANGE_QUANTITY",
	CHANGE_VARIANT = "CHANGE_VARIANT",
	SEND_CART = "SEND_CART"
}

export type actionType = null;
