export enum typeofAction {
	AUTH = "AUTH",

	NEWSLETTERS = "NEWSLETTERS",
	SIGN_IN = "SIGN_IN",
	SIGN_UP = "SIGN_UP",

	CARTSEND = "CARTSEND",
	ADD_TO_CART = "ADD_TO_CART",
	REMOVE_TO_CART = "ADD_TO_CART",
	CHANGE_QUANTITY = "CHANGE_QUANTITY",
	CHANGE_VARIANT = "CHANGE_VARIANT",
	SEND_CART = "SEND_CART",
	SEARCH = "SEARCH",

	//Gets

	GET_COLLECTION = "GET_COLLECTION",
	GET_COLLECTIONS = "GET_COLLECTIONS",
	GET_PROMOTE_COLLECTIONS = "GET_PROMOTE_COLLECTIONS",
	GET_WEAR = "GET_WEAR",
	GET_PRODUCT_ALL = "GET_PRODUCT_ALL",
	GET_PRODUCT_PREVIEW = "GET_PRODUCT_PREVIEW",
	GET_PROMOTE_PRODUCT = "GET_PROMOTE_PRODUCT"
}

export type actionType = null;
